name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      multiple: false
      options:
        - Critical! (*crit)
        - Important (*high)
        - Soon (*med)
        - Nice to have (*low)
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: app
    attributes:
      label: Which application is this request for?
      multiple: true
      options:
        - Decor (*decor)
        - PDI/Warranty (*pdi)
        - Mobile App (*mobile)
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description.
      description: Please describe the desired feature.
      placeholder: Tell us what you want!
      value: "Make it pop more!"
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant screenshots
      description: Please copy and paste any relevant screenshots
